spring:
  datasource:
    url: jdbc:postgresql://localhost/querydsl
    username: querydsl
    password: querydsl
  flyway:
    user: querydsl
    password: querydsl
    validate-on-migrate: true
  jpa:
    generate-ddl: true
    properties:
#      hibernate.ddl-auto: validate # Use this when using flyway for database creation
      hibernate.ddl-auto: create # Use this to see what would Hibernate create in database.
      hibernate.temp.use_jdbc_metadata_defaults: false # this removes warning "java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented."
      hibernate.use_sql_comments: true
      hibernate.format_sql: true
      hibernate.type: trace # log sql values
    show-sql: true